### ISSUE TITLE
Upstream changes have broken Logger calls to netconf

### ISSUE THREAD

**Issue by zachfi** [scottdware/go-junos#27]
```
../../go/src/github.com/scottdware/go-junos/junos.go:164:23: undefined: netconf.Logger
../../go/src/github.com/scottdware/go-junos/junos.go:166:4: undefined: netconf.SetLog
```

**Comment by bucklander** [comment]
👍 Specifically, this one: https://github.com/Juniper/go-netconf/commit/3e51c371774c49664923cdf92d2fbc16dce44a29

Looking for some time maybe drop in a fix.

**Comment by bucklander** [comment]
https://github.com/scottdware/go-junos/pull/28

**Comment by scottdware** [comment]
Fixed by merging your pull request! Thank you very much!
