### ISSUE TITLE
jnpr.Views("...") or jnpr.View("...")

### ISSUE THREAD

**Issue by MaxBear** [scottdware/go-junos#35]
There seem to be a documentation error on your readme : 

When I use jnpr.Views("..."), i get following errors: 
./main.go:21:20: jnpr.Views undefined (type *junos.Junos has no field or method Views)

When I change to jnpr.View("..."), things will work, if this is an error, can you fix it ?

**Comment by scottdware** [comment]
Thanks for catching this. Yeah, just a typo in the documentation. I'll change it :)

**Comment by scottdware** [comment]
Ok, I have updated the documentation in the README as well as the views.go file. Let me know if you need anything else!
