### ISSUE TITLE
bring your own SSH session/options

### ISSUE THREAD

**Issue by daemus** [scottdware/go-junos#40]
I think it would be nice to have a way to bring your own SSH session (net.Conn) or SSH config (ssh.ClientConfig).  For example, to specify SSH connection timeout, or connect via a proxy.

IMHO, it would make the most sense (for backwards compatibility) to refactor NewSession and move all the post session-establishment code into a new function, and create an additional function to deal with the new BYOS features.

Let me know if you agree with adding this functionality and I'll implement it and submit a PR.

**Comment by scottdware** [comment]
I like this idea a lot! Great work. I assume you've tested and things check out OK. I don't see any issues at all with the merge!

**Comment by daemus** [comment]
I have done some testing, using only the new functions.  I'll do some additional testing this week to cover all the different scenarios.
