### ISSUE TITLE
Possible to configure from string text

### ISSUE THREAD

**Issue by zachfi** [scottdware/go-junos#43]
Looking over the Config() method, its not clear to me if I can pass the config text in as a string.  I see loading a file and such, but say I were to render a template.  Would I be able to pass text in to the Config() method and have it get loaded to the device?

**Comment by scottdware** [comment]
You can use a `[]string` type to send configuration commands. So you could say, render a template, and use `fmt.Sprintf()` to replace the variable with the values you want. For example:

```Go
hostname := "junos-device"
cfg := []string{
    fmt.Sprintf("set system host-name %s", hostname),
    "set system login user admin class super-user",
}

err := jnpr.Config(cfg, "set", true)
if err != nil {
    fmt.Println(err)
}
```

**Comment by zachfi** [comment]
This works great.  I was able to use `text` for my purposes.  Thank you.
