### ISSUE TITLE
Client config could be nil if no password/keys are available. Triggers a nil reference.

### ISSUE THREAD

**Issue by itzurabhi** [scottdware/go-junos#48]
https://github.com/scottdware/go-junos/blob/6cb3105ba77c529a4f13968d876291184d4283de/junos.go#L170

returns a pointer regardless of the 2 if conditions.

https://github.com/scottdware/go-junos/blob/6cb3105ba77c529a4f13968d876291184d4283de/junos.go#L190

should return 

```config,errors.New("no credentials/keys available")```

**Comment by scottdware** [comment]
Thanks for catching this! I'll get this updated!
